## https://wiki.archlinux.org/title/GTK
## don't use inline comments

[Settings]
# disable recent file entries
####gtk-recent-files-enabled = 0

# scrollbars: fuck this retarded "zoom mode" (option needs ≥GTK+-3.14) (https://bugzilla.gnome.org/show_bug.cgi?id=728739#c9)
gtk-long-press-time = 60000
# scrollbars: scroll one page instead of jumping to position when clicking outside scrollbar
gtk-primary-button-warps-slider = false
# scrollbars: no retarded fading (gtk-4 has them hardcoded tho...)
gtk-overlay-scrolling = false

# no annoying bell on input events (https://bbs.archlinux.org/viewtopic.php?id=261938)
gtk-error-bell = false
gtk-enable-event-sounds = false
