# https://iamkate.com/data/12-bit-rainbow/

[colors.primary]
foreground = "#c9c9c9"
background = "#202020"
bright_foreground = "#e9e9e9"
[colors.normal]
black = "#404040"
red = "#aa3355"
green = "#44dd88"
yellow = "#ee9944"
blue = "#3366bb"
magenta = "#663399"
cyan = "#00bbcc"
white = "#a9a9a9"
[colors.bright]
black = "#5c5c5c"
red = "#cc6666"
green = "#99dd55"
yellow = "#eedd00"
blue = "#0099cc"
magenta = "#881177"
cyan = "#22ccbb"
white = "#c9c9c9"
